service: workout-logger-app
frameworkVersion: "3"

provider: ${file(./config/provider.yml)}

plugins: ${file(./config/plugins.yml)}

package:
  individually: true

layers: ${file(./config/layers.yml)}

functions: ${file(./config/functions.yml)}

resources: ${file(./config/resources.yml)}
