service: workout-logger-app
frameworkVersion: "3"

provider: ${file(./serverless/provider.yml)}

plugins: ${file(./serverless/plugins.yml)}

package:
  individually: true

layers: ${file(./serverless/layers.yml)}

functions: ${file(./serverless/functions.yml)}

resources: ${file(./serverless/resources.yml)}
