CreateUserForWorkoutAppFunction:
  name: ${sls:stage}-create-user-for-workout-app
  handler: src/functions/createUserForWorkoutApp.handler
  layers:
    - !Ref HelperResourcesLambdaLayer
  role: CreateUserFunctionRole
  events:
    - httpApi:
        path: /user
        method: post

GetWorkoutListFunction:
  name: ${sls:stage}-get-workout-list
  handler: src/functions/getWorkoutList.handler
  layers:
    - !Ref HelperResourcesLambdaLayer
  role: GetWorkoutListFunctionRole
  events:
    - httpApi:
        path: /{id}/{date}
        method: get

AddOrUpdateRepAndSetFunction:
  name: ${sls:stage}-add-or-update-rep-set
  handler: src/functions/addOrUpdateRepAndSet.handler
  layers:
    - !Ref HelperResourcesLambdaLayer
  role: AddOrUpdateRepAndSetFunctionRole
  events:
    - httpApi:
        path: /{id}/{date}
        method: put

DeleteAllWorkoutsFunction:
  name: ${sls:stage}-delete-all-workouts
  handler: src/functions/deleteAllWorkouts.handler
  layers:
    - !Ref HelperResourcesLambdaLayer
  role: DeleteAllWorkoutsFunctionRole
  events:
    - httpApi:
        path: /{id}
        method: delete

DeleteWorkoutAndUserFunction:
  name: ${sls:stage}-delete-workout-and-user
  handler: src/functions/deleteWorkoutAndUser.handler
  layers:
    - !Ref HelperResourcesLambdaLayer
  role: DeleteWorkoutAndUserFunctionRole
  events:
    - httpApi:
        path: /{id}/{date}
        method: delete
