CreateUserForWorkoutAppFunction:
  name: ${sls:stage}-create-user-for-workout-app
  handler: ../src/functions/createUserForWorkoutApp/index.handler
  layers:
    - !Ref HelperResourcesLambdaLayer
  events:
    - httpApi:
        path: /{data}
        method: post

GetWorkoutListFunction:
  name: ${sls:stage}-get-workout-list
  handler: ../src/functions/getWorkoutList/index.handler
  layers:
    - !Ref HelperResourcesLambdaLayer
  events:
    - httpApi:
        path: /{id}/all
        method: get

PutWorkoutRepAndSetFunction:
  name: ${sls:stage}-put-workout-rep-set
  handler: ../src/functions/putWorkoutRepAndSet/index.handler
  layers:
    - !Ref HelperResourcesLambdaLayer
  events:
    - httpApi:
        path: /{id}/{name}/{data}
        method: put

DeleteWorkoutFunction:
  name: ${sls:stage}-delete-workout
  handler: ../src/functions/deleteWorkout/index.handler
  layers:
    - !Ref HelperResourcesLambdaLayer
  events:
    - httpApi:
        path: /{id}/{name}
        method: delete
