CreateUserForWorkoutAppFunction:
  name: ${sls:stage}-create-user-for-workout-app
  handler: src/functions/createUserForWorkoutApp.handler
  layers:
    - !Ref HelperResourcesLambdaLayer
  role: CreateUserFunctionRole
  events:
    - httpApi:
        path: /user
        method: post

GetWorkoutListFunction:
  name: ${sls:stage}-get-workout-list
  handler: src/functions/getWorkoutList.handler
  layers:
    - !Ref HelperResourcesLambdaLayer
  role: GetWorkoutListFunctionRole
  events:
    - httpApi:
        path: /{id}/{date}
        method: get

PutWorkoutRepAndSetFunction:
  name: ${sls:stage}-put-workout-rep-set
  handler: src/functions/putWorkoutRepAndSet.handler
  layers:
    - !Ref HelperResourcesLambdaLayer
  events:
    - httpApi:
        path: /{id}
        method: put

DeleteWorkoutFunction:
  name: ${sls:stage}-delete-workout
  handler: src/functions/deleteWorkout.handler
  layers:
    - !Ref HelperResourcesLambdaLayer
  events:
    - httpApi:
        path: /{id}
        method: delete
