name: Deploy to AWS
on:
  push:
    branches:
      - main
      - production

env:
  AWS_REGION: ${{secrets.AWS_REGION}}
  STAGE: ${{ github.ref_name == 'main' && 'dev' || 'prod' }}
  AWS_ACCESS_KEY_ID: ${{ github.ref_name == 'main' && secrets.AWS_ACCESS_KEY_ID != '' && secrets.AWS_ACCESS_KEY_ID || secrets.PROD_AWS_ACCESS_KEY_ID != '' && secrets.PROD_AWS_ACCESS_KEY_ID || '' }}
  AWS_SECRET_ACCESS_KEY: ${{ github.ref_name == 'main' && secrets.AWS_SECRET_ACCESS_KEY != '' && secrets.AWS_SECRET_ACCESS_KEY || secrets.PROD_AWS_SECRET_ACCESS_KEY != '' && secrets.PROD_AWS_SECRET_ACCESS_KEY || '' }}

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "npm"

      - name: Configure AWS Authentication
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{env.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{env.AWS_SECRET_ACCESS_KEY}}

      - name: Install Plugin and Deploy
        uses: serverless/github-action@v3.2
        with:
          args: -c "serverless plugin install --name serverless-esbuild && serverless deploy --stage=${{ env.STAGE }} --verbose"
          entrypoint: /bin/sh
